// AUTO-GENERATED FILE. DO NOT EDIT.
// Generated by scripts/generate-plugin-registry.mjs

use crate::encoders::FormatEncoder;

#[path = "../../../../plugins/athena/slicing/rust/encoder_impl.rs"]
pub mod athena_encoder;

#[path = "../../../../plugins/ctb/slicing/rust/encoder_impl.rs"]
pub mod ctb_encoder;

pub fn build_generated_plugin_encoders() -> Vec<Box<dyn FormatEncoder>> {
    [
        athena_encoder::create_plugin_encoder(),
        ctb_encoder::create_plugin_encoder(),
    ]
    .into_iter()
    .flat_map(|encoders| encoders)
    .collect()
}
