// AUTO-GENERATED FILE. DO NOT EDIT.
// Generated by scripts/generate-plugin-registry.mjs

use crate::encoders::FormatEncoder;

#[path = "../../../../plugins/athena/slicing/rust/encoder_impl.rs"]
pub mod athena_encoder;

pub fn build_generated_plugin_encoders() -> Vec<Box<dyn FormatEncoder>> {
    vec![
        athena_encoder::create_plugin_encoder(),
    ]
}
