//! Reading a stored preview out of a container, from its declaration.
//!
//! Every file type the app writes declares where its preview lives in
//! `outputFileTypes.json` (core: `src/config/core-output-file-types.json`; plugin:
//! `plugins/<id>/outputFileTypes.json`). `scripts/generate-plugin-registry.mjs`
//! validates those declarations and compiles them into
//! [`generated_output_file_types.json`], which this module reads once and
//! interprets. Nothing here knows a format: a new container gets a shell thumbnail
//! by declaring itself.
//!
//! The grammar is deliberately small — a chunk table whose entries point at a stored
//! PNG, optionally zlib-compressed or base64 inside a JSON payload, optionally
//! ranked by a role in the entry flags. That covers the formats in the tree and the
//! print containers around them; a format whose preview must be *computed* rather
//! than found cannot be described this way and is not supported yet.

use std::io::{Read, Seek, SeekFrom};
use std::sync::LazyLock;

use serde_json::Value;

use crate::{ThumbnailError, PNG_SIGNATURE};

/// The table the registry generator compiled in. Regenerated by
/// `npm run generate:plugin-registry`; absent from a checkout that has never built.
const GENERATED_OUTPUT_FILE_TYPES: &str = include_str!("generated_output_file_types.json");

/// One file type the app can write, as declared by its owner.
pub struct OutputFileType {
    file_extension: String,
    mime_type: String,
    uti: String,
    display_name: String,
    locator: Locator,
}

impl OutputFileType {
    /// The lowercase extension, leading dot included.
    pub fn file_extension(&self) -> &str {
        &self.file_extension
    }

    /// The media type the file managers should use.
    pub fn mime_type(&self) -> &str {
        &self.mime_type
    }

    /// The macOS uniform type identifier.
    pub fn uti(&self) -> &str {
        &self.uti
    }

    /// The label the file managers show.
    pub fn display_name(&self) -> &str {
        &self.display_name
    }

    /// Whether this is the container a file starts with.
    fn matches_magic(&self, head: &[u8]) -> bool {
        !self.locator.magic.is_empty() && head.starts_with(&self.locator.magic)
    }

    /// Extract this format's preview as raw PNG bytes.
    pub fn extract<R: Read + Seek>(&self, reader: &mut R) -> Result<Vec<u8>, ThumbnailError> {
        self.locator.extract(reader, &self.file_extension)
    }
}

/// Every declared file type, core first, in the generated table's order.
pub fn output_file_types() -> &'static [OutputFileType] {
    static TYPES: LazyLock<Vec<OutputFileType>> = LazyLock::new(|| {
        let parsed: Value = serde_json::from_str(GENERATED_OUTPUT_FILE_TYPES)
            .expect("generated_output_file_types.json is not valid JSON; run `npm run generate:plugin-registry`");
        let entries = parsed
            .as_array()
            .expect("generated_output_file_types.json is not an array; run `npm run generate:plugin-registry`");

        entries
            .iter()
            .map(|entry| OutputFileType {
                file_extension: string_field(entry, "fileExtension"),
                mime_type: string_field(entry, "mimeType"),
                uti: string_field(entry, "uti"),
                display_name: string_field(entry, "displayName"),
                locator: Locator::from_json(&entry["thumbnail"]),
            })
            .collect()
    });

    &TYPES
}

/// The file type whose magic a container starts with, if any.
pub fn output_file_type_for(head: &[u8]) -> Option<&'static OutputFileType> {
    output_file_types().iter().find(|file_type| file_type.matches_magic(head))
}

// ---------------------------------------------------------------------------
// The declaration, as this interpreter wants it
// ---------------------------------------------------------------------------

#[derive(Clone, Copy)]
enum Width {
    U16,
    U32,
    U64,
}

impl Width {
    fn from_json(value: &Value) -> Self {
        match value.as_str() {
            Some("u16") => Width::U16,
            Some("u32") => Width::U32,
            Some("u64") => Width::U64,
            other => panic!("thumbnail declaration has an unknown field width: {other:?}"),
        }
    }

    fn bytes(self) -> usize {
        match self {
            Width::U16 => 2,
            Width::U32 => 4,
            Width::U64 => 8,
        }
    }
}

#[derive(Clone, Copy)]
struct Field {
    width: Width,
    at: usize,
}

impl Field {
    fn from_json(value: &Value) -> Self {
        Self {
            width: Width::from_json(&value["type"]),
            at: number_field(value, "at") as usize,
        }
    }

    /// Read the field out of a buffer, or `None` when it does not fit.
    fn read(&self, bytes: &[u8]) -> Option<u64> {
        let slice = bytes.get(self.at..self.at + self.width.bytes())?;
        Some(match self.width {
            Width::U16 => u64::from(u16::from_le_bytes(slice.try_into().unwrap())),
            Width::U32 => u64::from(u32::from_le_bytes(slice.try_into().unwrap())),
            Width::U64 => u64::from_le_bytes(slice.try_into().unwrap()),
        })
    }
}

struct DirectorySpec {
    /// Fixed offset, or read from the header.
    offset_fixed: Option<u64>,
    offset_field: Option<Field>,
    count: Field,
    entry_size: u64,
}

struct EntrySpec {
    type_at: usize,
    offset: Field,
    sizes: Vec<Field>,
    index: Option<(Field, u64)>,
    compression: Option<CompressionSpec>,
    flags: Option<FlagsSpec>,
}

struct CompressionSpec {
    field: Field,
    stored: Vec<u64>,
    zlib: Vec<u64>,
}

struct FlagsSpec {
    field: Field,
    sealed_bit: Option<u32>,
    role_mask: Option<u64>,
    role_order: Vec<u64>,
}

enum PayloadSpec {
    Png,
    JsonBase64(Vec<String>),
}

struct TrailerSpec {
    magic: Vec<u8>,
    size: u64,
}

struct Locator {
    magic: Vec<u8>,
    version: Option<(Field, Option<u64>, Option<u64>)>,
    directory: DirectorySpec,
    entry: EntrySpec,
    preview_chunks: Vec<Vec<u8>>,
    payload: PayloadSpec,
    trailer: Option<TrailerSpec>,
}

impl Locator {
    fn from_json(value: &Value) -> Self {
        let directory = &value["directory"];
        let entry = &value["entry"];

        let offset_fixed = directory["offset"]["fixed"].as_u64();
        let offset_field = if offset_fixed.is_some() {
            None
        } else {
            Some(Field::from_json(&directory["offset"]))
        };

        let version = value.get("version").filter(|v| !v.is_null()).map(|v| {
            (
                Field::from_json(v),
                v["equals"].as_u64(),
                v["atLeast"].as_u64(),
            )
        });

        let flags = entry.get("flags").filter(|v| !v.is_null()).map(|flags| FlagsSpec {
            field: Field::from_json(flags),
            sealed_bit: flags["sealedBit"].as_u64().map(|bit| bit as u32),
            role_mask: flags["roleMask"].as_u64(),
            role_order: flags["roleOrder"]
                .as_array()
                .map(|values| values.iter().filter_map(Value::as_u64).collect())
                .unwrap_or_default(),
        });

        let compression = entry.get("compression").filter(|v| !v.is_null()).map(|c| CompressionSpec {
            field: Field::from_json(c),
            stored: codes_of(c, "stored"),
            zlib: codes_of(c, "zlib"),
        });

        Self {
            magic: string_field(value, "magic").into_bytes(),
            version,
            directory: DirectorySpec {
                offset_fixed,
                offset_field,
                count: Field::from_json(&directory["count"]),
                entry_size: number_field(directory, "entrySize"),
            },
            entry: EntrySpec {
                type_at: number_field(&entry["type"], "at") as usize,
                offset: Field::from_json(&entry["offset"]),
                sizes: entry["size"]
                    .as_array()
                    .expect("thumbnail declaration has no size fields")
                    .iter()
                    .map(Field::from_json)
                    .collect(),
                index: entry.get("index").filter(|v| !v.is_null()).map(|index| {
                    (Field::from_json(index), number_field(index, "value"))
                }),
                compression,
                flags,
            },
            preview_chunks: value["previewChunks"]
                .as_array()
                .expect("thumbnail declaration names no preview chunk")
                .iter()
                .filter_map(Value::as_str)
                .map(str::as_bytes)
                .map(<[u8]>::to_vec)
                .collect(),
            payload: match value["payload"]["encoding"].as_str() {
                Some("png") => PayloadSpec::Png,
                Some("json-base64") => PayloadSpec::JsonBase64(
                    value["payload"]["jsonPath"]
                        .as_array()
                        .expect("thumbnail declaration has no JSON path")
                        .iter()
                        .filter_map(Value::as_str)
                        .map(str::to_string)
                        .collect(),
                ),
                other => panic!("thumbnail declaration has an unknown payload encoding: {other:?}"),
            },
            trailer: value.get("trailer").filter(|v| !v.is_null()).map(|trailer| TrailerSpec {
                magic: string_field(trailer, "magic").into_bytes(),
                size: number_field(trailer, "size"),
            }),
        }
    }

    /// Read the best stored preview, in the declaration's own terms.
    fn extract<R: Read + Seek>(
        &self,
        reader: &mut R,
        extension: &str,
    ) -> Result<Vec<u8>, ThumbnailError> {
        let malformed = |reason: String| ThumbnailError::Malformed(format!("{extension}: {reason}"));

        let file_len = reader.seek(SeekFrom::End(0))?;

        // ── Header ─────────────────────────────────────────────────────────
        reader.seek(SeekFrom::Start(0))?;
        let mut header = vec![0u8; self.magic.len().max(64)];
        let read = reader.read(&mut header)?;
        header.truncate(read);

        if !header.starts_with(&self.magic) {
            return Err(ThumbnailError::UnsupportedFile);
        }

        if let Some((field, equals, at_least)) = self.version {
            let version = field
                .read(&header)
                .ok_or_else(|| malformed("the header is too short for its version field".to_string()))?;
            if let Some(expected) = equals {
                if version != expected {
                    return Err(malformed(format!("version {version} is not the declared {expected}")));
                }
            }
            if let Some(minimum) = at_least {
                if version < minimum {
                    return Err(malformed(format!("version {version} is below the declared {minimum}")));
                }
            }
        }

        // ── Trailer ────────────────────────────────────────────────────────
        if let Some(trailer) = &self.trailer {
            if file_len < trailer.size {
                return Err(malformed("the file is shorter than its trailer".to_string()));
            }
            reader.seek(SeekFrom::Start(file_len - trailer.size))?;
            let mut tail = vec![0u8; trailer.size as usize];
            reader.read_exact(&mut tail)?;
            if !tail.starts_with(&trailer.magic) {
                return Err(malformed("the file does not end with the declared trailer".to_string()));
            }
        }

        // ── Chunk table ────────────────────────────────────────────────────
        let directory_offset = match (self.directory.offset_fixed, self.directory.offset_field) {
            (Some(fixed), _) => fixed,
            (None, Some(field)) => field
                .read(&header)
                .ok_or_else(|| malformed("the header is too short for the table offset".to_string()))?,
            (None, None) => return Err(malformed("the declaration has no table offset".to_string())),
        };
        let entry_count = self
            .directory
            .count
            .read(&header)
            .ok_or_else(|| malformed("the header is too short for the entry count".to_string()))?;

        let table_len = entry_count
            .checked_mul(self.directory.entry_size)
            .ok_or_else(|| malformed("the table length overflows".to_string()))?;
        let table_end = directory_offset
            .checked_add(table_len)
            .ok_or_else(|| malformed("the table offset overflows".to_string()))?;
        // Compared the safe way round: a corrupt count would otherwise wrap the bound
        // in a release build instead of being refused.
        if table_end > file_len {
            return Err(malformed("the chunk table lies outside the file".to_string()));
        }

        reader.seek(SeekFrom::Start(directory_offset))?;
        let mut table = vec![0u8; table_len as usize];
        reader.read_exact(&mut table)?;

        // ── Pick the best preview ──────────────────────────────────────────
        let mut candidates: Vec<Candidate> = Vec::new();
        for index in 0..entry_count {
            let base = (index * self.directory.entry_size) as usize;
            let Some(entry) = table.get(base..base + self.directory.entry_size as usize) else {
                continue;
            };

            let chunk = entry.get(self.entry.type_at..).unwrap_or_default();
            if !self.preview_chunks.iter().any(|preview| chunk.starts_with(preview)) {
                continue;
            }

            if let Some((field, expected)) = &self.entry.index {
                if field.read(entry) != Some(*expected) {
                    continue;
                }
            }

            let mut rank = 0u64;
            if let Some(flags) = &self.entry.flags {
                let raw = flags.field.read(entry).unwrap_or(0);
                if let Some(sealed_bit) = flags.sealed_bit {
                    if raw & (1 << sealed_bit) != 0 {
                        continue; // needs the file's key; not a thumbnail this reader can show
                    }
                }
                if let Some(mask) = flags.role_mask {
                    let role = raw & mask;
                    match flags.role_order.iter().position(|listed| *listed == role) {
                        Some(position) => rank = position as u64,
                        None => continue, // a role the format does not use for previews
                    }
                }
            }

            let Some(offset) = self.entry.offset.read(entry) else {
                continue;
            };
            let Some(size) = self
                .entry
                .sizes
                .iter()
                .filter_map(|field| field.read(entry))
                .find(|value| *value != 0)
            else {
                continue;
            };

            if size == 0 || offset > file_len || size > file_len - offset {
                continue;
            }

            let compression = self
                .entry
                .compression
                .as_ref()
                .and_then(|spec| spec.field.read(entry));

            candidates.push(Candidate {
                rank,
                index,
                offset,
                size,
                compression,
            });
        }

        // Best role first, table order breaking ties, so the choice is deterministic.
        candidates.sort_by_key(|candidate| (candidate.rank, candidate.index));

        for candidate in candidates {
            reader.seek(SeekFrom::Start(candidate.offset))?;
            let mut payload = vec![0u8; candidate.size as usize];
            reader.read_exact(&mut payload)?;

            // A code the declaration does not list is refused rather than guessed at:
            // reading a compressed payload as pixels would hand the shell garbage.
            if let Some(spec) = self.entry.compression.as_ref() {
                match candidate.compression {
                    Some(code) if spec.stored.contains(&code) => {}
                    Some(code) if spec.zlib.contains(&code) => {
                        payload = inflate(&payload).map_err(malformed)?;
                    }
                    Some(code) => {
                        return Err(malformed(format!("unknown compression code {code}")));
                    }
                    None => {}
                }
            }

            match &self.payload {
                PayloadSpec::Png => {
                    // A payload that is not a PNG is not a preview this reader can hand
                    // to the shell; keep looking in case a better-formed one follows.
                    if payload.starts_with(&PNG_SIGNATURE) {
                        return Ok(payload);
                    }
                }
                PayloadSpec::JsonBase64(path) => {
                    if let Some(png) = png_from_json(&payload, path).map_err(malformed)? {
                        return Ok(png);
                    }
                }
            }
        }

        Err(ThumbnailError::NoThumbnail)
    }
}

struct Candidate {
    rank: u64,
    index: u64,
    offset: u64,
    size: u64,
    compression: Option<u64>,
}

/// The base64 PNG at a JSON path inside a chunk payload, or `None` when that path is
/// absent — an extension chunk without a preview is not an error, merely unhelpful.
fn png_from_json(payload: &[u8], path: &[String]) -> Result<Option<Vec<u8>>, String> {
    let parsed: Value = serde_json::from_slice(payload).map_err(|error| format!("JSON parse failed: {error}"))?;

    let mut cursor = &parsed;
    for key in path {
        match cursor.get(key) {
            Some(next) => cursor = next,
            None => return Ok(None),
        }
    }

    let Some(encoded) = cursor.as_str() else {
        return Ok(None);
    };

    use base64::engine::general_purpose::STANDARD;
    use base64::Engine;
    let decoded = STANDARD
        .decode(encoded)
        .map_err(|error| format!("base64 decode failed: {error}"))?;

    Ok(decoded.starts_with(&PNG_SIGNATURE).then_some(decoded))
}

fn inflate(payload: &[u8]) -> Result<Vec<u8>, String> {
    use flate2::read::ZlibDecoder;
    use std::io::Cursor;

    let mut decoded = Vec::new();
    ZlibDecoder::new(Cursor::new(payload))
        .read_to_end(&mut decoded)
        .map_err(|error| format!("decompression failed: {error}"))?;
    Ok(decoded)
}

fn codes_of(value: &Value, key: &str) -> Vec<u64> {
    value
        .get(key)
        .and_then(Value::as_array)
        .map(|codes| codes.iter().filter_map(Value::as_u64).collect())
        .unwrap_or_default()
}

fn string_field(value: &Value, key: &str) -> String {
    value[key]
        .as_str()
        .unwrap_or_else(|| panic!("thumbnail declaration has no string field {key}"))
        .to_string()
}

fn number_field(value: &Value, key: &str) -> u64 {
    value[key]
        .as_u64()
        .unwrap_or_else(|| panic!("thumbnail declaration has no numeric field {key}"))
}
