/* AUTO-GENERATED FILE. DO NOT EDIT.
 * Generated by scripts/generate-builtin-simple-plugins.mjs
 */
import type { PluginManifest } from '@/features/plugins/pluginRegistry';

const GENERATED_BUILTIN_SIMPLE_PLUGIN_MANIFESTS_RAW = Object.freeze([
  {
    "schemaVersion": 1,
    "id": "elegoo-printer-profiles",
    "name": "ELEGOO Printer Profiles",
    "version": "0.2.0",
    "description": "Simple DragonFruit plugin that adds curated ELEGOO printer presets for CTB workflows.",
    "author": "Open Resin Alliance",
    "homepage": "https://github.com/Open-Resin-Alliance/df-plugin-elegoo",
    "printerPresets": [
      {
        "presetId": "elegoo-mars-3-ctb",
        "profileVersion": 1,
        "manufacturer": "ELEGOO",
        "family": "Mars",
        "name": "Mars 3",
        "imageAssetPath": "/plugins/elegoo/printers/assets/mars/mars-3.png",
        "antiAliasing": true,
        "hasCamera": false,
        "networkSupport": null,
        "networkFilter": "Mars 3",
        "buildVolumeMm": {
          "width": null,
          "depth": null,
          "height": 175
        },
        "pixelSize": {
          "x": 35,
          "y": 35
        },
        "display": {
          "resolutionX": 4098,
          "resolutionY": 2560,
          "outputFormat": ".ctb",
          "formatVersion": "v5enc",
          "settingsMode": "twostage",
          "mirrorX": true,
          "mirrorY": false
        }
      },
      {
        "presetId": "elegoo-mars-3-pro-ctb",
        "profileVersion": 1,
        "manufacturer": "ELEGOO",
        "family": "Mars",
        "name": "Mars 3 Pro",
        "imageAssetPath": "/plugins/elegoo/printers/assets/mars/mars-3.png",
        "antiAliasing": true,
        "hasCamera": false,
        "networkSupport": null,
        "networkFilter": "Mars 3",
        "buildVolumeMm": {
          "width": null,
          "depth": null,
          "height": 175
        },
        "pixelSize": {
          "x": 35,
          "y": 35
        },
        "display": {
          "resolutionX": 4098,
          "resolutionY": 2560,
          "outputFormat": ".ctb",
          "formatVersion": "v5enc",
          "settingsMode": "twostage",
          "mirrorX": true,
          "mirrorY": false
        }
      },
      {
        "presetId": "elegoo-mars-4-ctb",
        "profileVersion": 1,
        "manufacturer": "ELEGOO",
        "family": "Mars",
        "name": "Mars 4",
        "imageAssetPath": "/plugins/elegoo/printers/assets/mars/mars-4.png",
        "antiAliasing": true,
        "hasCamera": false,
        "networkSupport": null,
        "networkFilter": "Mars 4",
        "buildVolumeMm": {
          "width": null,
          "depth": null,
          "height": 175
        },
        "pixelSize": {
          "x": 18,
          "y": 18
        },
        "display": {
          "resolutionX": 8520,
          "resolutionY": 4320,
          "outputFormat": ".ctb",
          "formatVersion": "v5enc",
          "settingsMode": "twostage",
          "mirrorX": true,
          "mirrorY": false
        }
      },
      {
        "presetId": "elegoo-mars-4-dlp-ctb",
        "profileVersion": 1,
        "manufacturer": "ELEGOO",
        "family": "Mars",
        "name": "Mars 4 DLP",
        "imageAssetPath": "/plugins/elegoo/printers/assets/mars/mars-4-max.png",
        "antiAliasing": true,
        "hasCamera": false,
        "networkSupport": null,
        "networkFilter": "Mars 4",
        "buildVolumeMm": {
          "width": null,
          "depth": null,
          "height": 150
        },
        "pixelSize": {
          "x": 51.875,
          "y": 51.875
        },
        "display": {
          "resolutionX": 2560,
          "resolutionY": 1440,
          "outputFormat": ".ctb",
          "formatVersion": "v5enc",
          "settingsMode": "twostage",
          "mirrorX": true,
          "mirrorY": false
        }
      },
      {
        "presetId": "elegoo-mars-4-max-ctb",
        "profileVersion": 1,
        "manufacturer": "ELEGOO",
        "family": "Mars",
        "name": "Mars 4 Max",
        "imageAssetPath": "/plugins/elegoo/printers/assets/mars/mars-4-max.png",
        "antiAliasing": true,
        "hasCamera": false,
        "networkSupport": null,
        "networkFilter": "Mars 4",
        "buildVolumeMm": {
          "width": null,
          "depth": null,
          "height": 150
        },
        "pixelSize": {
          "x": 34,
          "y": 34
        },
        "display": {
          "resolutionX": 5760,
          "resolutionY": 3600,
          "outputFormat": ".ctb",
          "formatVersion": "v5enc",
          "settingsMode": "twostage",
          "mirrorX": true,
          "mirrorY": false
        }
      },
      {
        "presetId": "elegoo-mars-4-ultra-ctb",
        "profileVersion": 1,
        "manufacturer": "ELEGOO",
        "family": "Mars",
        "name": "Mars 4 Ultra",
        "imageAssetPath": "/plugins/elegoo/printers/assets/mars/mars-4-ultra.png",
        "antiAliasing": true,
        "hasCamera": false,
        "networkSupport": "sdcp",
        "networkFilter": "Mars 4",
        "buildVolumeMm": {
          "width": null,
          "depth": null,
          "height": 165
        },
        "pixelSize": {
          "x": 18,
          "y": 18
        },
        "display": {
          "resolutionX": 8520,
          "resolutionY": 4320,
          "outputFormat": ".ctb",
          "formatVersion": "v5enc",
          "settingsMode": "twostage",
          "mirrorX": true,
          "mirrorY": false
        }
      },
      {
        "presetId": "elegoo-mars-5-ctb",
        "profileVersion": 1,
        "manufacturer": "ELEGOO",
        "family": "Mars",
        "name": "Mars 5",
        "imageAssetPath": "/plugins/elegoo/printers/assets/mars/mars-5.png",
        "antiAliasing": true,
        "hasCamera": false,
        "networkSupport": null,
        "networkFilter": "Mars 5",
        "buildVolumeMm": {
          "width": null,
          "depth": null,
          "height": 165
        },
        "pixelSize": {
          "x": 35,
          "y": 35
        },
        "display": {
          "resolutionX": 4098,
          "resolutionY": 2560,
          "outputFormat": ".ctb",
          "formatVersion": "v5enc",
          "settingsMode": "twostage",
          "mirrorX": true,
          "mirrorY": false
        }
      },
      {
        "presetId": "elegoo-mars-5-ultra-ctb",
        "profileVersion": 2,
        "manufacturer": "ELEGOO",
        "family": "Mars",
        "name": "Mars 5 Ultra",
        "imageAssetPath": "/plugins/elegoo/printers/assets/mars/mars-5-ultra.png",
        "antiAliasing": true,
        "hasCamera": true,
        "networkSupport": "sdcp",
        "networkFilter": "Mars 5",
        "buildVolumeMm": {
          "width": null,
          "depth": null,
          "height": 165
        },
        "pixelSize": {
          "x": 18,
          "y": 18
        },
        "display": {
          "resolutionX": 8520,
          "resolutionY": 4320,
          "outputFormat": ".ctb",
          "formatVersion": "v5enc",
          "settingsMode": "simple",
          "mirrorX": true,
          "mirrorY": false
        }
      },
      {
        "presetId": "elegoo-saturn-2-ctb",
        "profileVersion": 1,
        "manufacturer": "ELEGOO",
        "family": "Saturn",
        "name": "Saturn 2",
        "imageAssetPath": "/plugins/elegoo/printers/assets/saturn/saturn-2.png",
        "antiAliasing": true,
        "hasCamera": false,
        "networkSupport": null,
        "networkFilter": "Saturn 2",
        "buildVolumeMm": {
          "width": null,
          "depth": null,
          "height": 250
        },
        "pixelSize": {
          "x": 28.5,
          "y": 28.5
        },
        "display": {
          "resolutionX": 7680,
          "resolutionY": 4320,
          "outputFormat": ".ctb",
          "formatVersion": "v5enc",
          "settingsMode": "twostage",
          "mirrorX": true,
          "mirrorY": false
        }
      },
      {
        "presetId": "elegoo-saturn-2-14k-ctb",
        "profileVersion": 1,
        "manufacturer": "ELEGOO",
        "family": "Saturn",
        "name": "Saturn 2 14K",
        "imageAssetPath": "/plugins/elegoo/printers/assets/saturn/saturn-2.png",
        "antiAliasing": true,
        "hasCamera": false,
        "networkSupport": null,
        "networkFilter": "Saturn 2",
        "buildVolumeMm": {
          "width": null,
          "depth": null,
          "height": 250
        },
        "pixelSize": {
          "x": 16.8,
          "y": 24.8
        },
        "display": {
          "resolutionX": 13320,
          "resolutionY": 5120,
          "outputFormat": ".ctb",
          "formatVersion": "v5enc",
          "settingsMode": "twostage",
          "mirrorX": true,
          "mirrorY": false
        }
      },
      {
        "presetId": "elegoo-saturn-3-ctb",
        "profileVersion": 1,
        "manufacturer": "ELEGOO",
        "family": "Saturn",
        "name": "Saturn 3",
        "imageAssetPath": "/plugins/elegoo/printers/assets/saturn/saturn-3.png",
        "antiAliasing": true,
        "hasCamera": false,
        "networkSupport": null,
        "networkFilter": "Saturn 3",
        "buildVolumeMm": {
          "width": null,
          "depth": null,
          "height": 249.7
        },
        "pixelSize": {
          "x": 19,
          "y": 24
        },
        "display": {
          "resolutionX": 11520,
          "resolutionY": 5120,
          "outputFormat": ".ctb",
          "formatVersion": "v5enc",
          "settingsMode": "twostage",
          "mirrorX": true,
          "mirrorY": false
        }
      },
      {
        "presetId": "elegoo-saturn-3-ultra-ctb",
        "profileVersion": 1,
        "manufacturer": "ELEGOO",
        "family": "Saturn",
        "name": "Saturn 3 Ultra",
        "imageAssetPath": "/plugins/elegoo/printers/assets/saturn/saturn-3-ultra.png",
        "antiAliasing": true,
        "hasCamera": false,
        "networkSupport": "sdcp",
        "networkFilter": "Saturn 3",
        "buildVolumeMm": {
          "width": null,
          "depth": null,
          "height": 260
        },
        "pixelSize": {
          "x": 19,
          "y": 24
        },
        "display": {
          "resolutionX": 11520,
          "resolutionY": 5120,
          "outputFormat": ".ctb",
          "formatVersion": "v5enc",
          "settingsMode": "twostage",
          "mirrorX": true,
          "mirrorY": false
        }
      },
      {
        "presetId": "elegoo-saturn-4-ctb",
        "profileVersion": 1,
        "manufacturer": "ELEGOO",
        "family": "Saturn",
        "name": "Saturn 4",
        "imageAssetPath": "/plugins/elegoo/printers/assets/saturn/saturn-4.png",
        "antiAliasing": true,
        "hasCamera": false,
        "networkSupport": null,
        "networkFilter": "Saturn 4",
        "buildVolumeMm": {
          "width": null,
          "depth": null,
          "height": 220
        },
        "pixelSize": {
          "x": 19,
          "y": 24
        },
        "display": {
          "resolutionX": 11520,
          "resolutionY": 5120,
          "outputFormat": ".ctb",
          "formatVersion": "v5enc",
          "settingsMode": "twostage",
          "mirrorX": true,
          "mirrorY": false
        }
      },
      {
        "presetId": "elegoo-saturn-4-ultra-ctb",
        "profileVersion": 2,
        "manufacturer": "ELEGOO",
        "family": "Saturn",
        "name": "Saturn 4 Ultra",
        "imageAssetPath": "/plugins/elegoo/printers/assets/saturn/saturn-4-ultra.png",
        "antiAliasing": true,
        "hasCamera": true,
        "networkSupport": "sdcp",
        "networkFilter": "Saturn 4",
        "buildVolumeMm": {
          "width": null,
          "depth": null,
          "height": 220
        },
        "pixelSize": {
          "x": 19,
          "y": 24
        },
        "display": {
          "resolutionX": 11520,
          "resolutionY": 5120,
          "outputFormat": ".ctb",
          "formatVersion": "v5enc",
          "settingsMode": "simple",
          "mirrorX": true,
          "mirrorY": false
        }
      },
      {
        "presetId": "elegoo-saturn-4-ultra-16k-ctb",
        "profileVersion": 2,
        "manufacturer": "ELEGOO",
        "family": "Saturn",
        "name": "Saturn 4 Ultra 16K",
        "imageAssetPath": "/plugins/elegoo/printers/assets/saturn/saturn-4-ultra-16k.png",
        "antiAliasing": true,
        "hasCamera": false,
        "networkSupport": "sdcp",
        "networkFilter": "Saturn 4",
        "buildVolumeMm": {
          "width": null,
          "depth": null,
          "height": 220
        },
        "pixelSize": {
          "x": 14,
          "y": 19
        },
        "display": {
          "resolutionX": 15120,
          "resolutionY": 6230,
          "outputFormat": ".ctb",
          "formatVersion": "v5enc",
          "settingsMode": "simple",
          "mirrorX": true,
          "mirrorY": false
        }
      },
      {
        "presetId": "elegoo-jupiter-ctb",
        "profileVersion": 1,
        "manufacturer": "ELEGOO",
        "family": "Jupiter",
        "name": "Jupiter",
        "imageAssetPath": "/plugins/elegoo/printers/assets/jupiter/jupiter.png",
        "antiAliasing": true,
        "hasCamera": false,
        "networkSupport": null,
        "networkFilter": "Jupiter",
        "buildVolumeMm": {
          "width": null,
          "depth": null,
          "height": 300
        },
        "pixelSize": {
          "x": 51,
          "y": 51
        },
        "display": {
          "resolutionX": 5448,
          "resolutionY": 3064,
          "outputFormat": ".ctb",
          "formatVersion": "v5",
          "settingsMode": "twostage",
          "mirrorX": true,
          "mirrorY": false
        }
      },
      {
        "presetId": "elegoo-jupiter-se-ctb",
        "profileVersion": 1,
        "manufacturer": "ELEGOO",
        "family": "Jupiter",
        "name": "Jupiter SE",
        "imageAssetPath": "/plugins/elegoo/printers/assets/jupiter/jupiter-se.png",
        "antiAliasing": true,
        "hasCamera": false,
        "networkSupport": null,
        "networkFilter": "Jupiter",
        "buildVolumeMm": {
          "width": null,
          "depth": null,
          "height": 300
        },
        "pixelSize": {
          "x": 51,
          "y": 51
        },
        "display": {
          "resolutionX": 5448,
          "resolutionY": 3064,
          "outputFormat": ".ctb",
          "formatVersion": "v5",
          "settingsMode": "twostage",
          "mirrorX": true,
          "mirrorY": false
        }
      }
    ],
    "materialTemplates": []
  }
]);

export const GENERATED_BUILTIN_SIMPLE_PLUGIN_MANIFESTS = GENERATED_BUILTIN_SIMPLE_PLUGIN_MANIFESTS_RAW as unknown as readonly PluginManifest[];
