/* AUTO-GENERATED FILE. DO NOT EDIT.
 * Generated by scripts/generate-plugin-registry.mjs
 */
import type { ComplexPluginDefinition } from '@/features/plugins/complexPluginContracts';
import athenaDefinition from '../../../plugins/athena/pluginDefinition';

export const GENERATED_BUILTIN_COMPLEX_PLUGIN_ID_ALLOWLIST = Object.freeze([
  'athena'
]) as readonly string[];

export const GENERATED_COMPLEX_PLUGIN_ALLOWLIST_SHA256 = '2d47bbc204f2ea9e6e3eb4ad016b01e388acde514aa41fd775e9cdb8015c1396' as const;

export const GENERATED_BUILTIN_COMPLEX_PLUGIN_DEFINITIONS: ComplexPluginDefinition[] = [
  athenaDefinition
];
