/* AUTO-GENERATED FILE. DO NOT EDIT.
 * Generated by scripts/generate-plugin-registry.mjs
 */
import type { PluginNetworkOperationHandler } from '@/features/plugins/networkPluginRegistry';
import { handlePluginNetworkOperation as athena_network_handler } from '../../../plugins/athena/network/networkHandlers';

export type GeneratedBuiltinComplexPluginNetworkHandler = {
  pluginId: string;
  handler: PluginNetworkOperationHandler;
};

export const GENERATED_BUILTIN_COMPLEX_PLUGIN_NETWORK_HANDLERS: GeneratedBuiltinComplexPluginNetworkHandler[] = [
  { pluginId: 'athena', handler: athena_network_handler }
];
