/* AUTO-GENERATED FILE. DO NOT EDIT.
 * Generated by scripts/generate-plugin-registry.mjs
 */
import type { PluginUploadHandler } from '@/features/plugins/pluginUploadBridge';
import { uploadPrintJobWithProgress as athena_upload_handler } from '../../../plugins/athena/network';

export type GeneratedBuiltinComplexPluginUploadHandler = {
  pluginId: string;
  handler: PluginUploadHandler;
};

export const GENERATED_BUILTIN_COMPLEX_PLUGIN_UPLOAD_HANDLERS: GeneratedBuiltinComplexPluginUploadHandler[] = [
  { pluginId: 'athena', handler: athena_upload_handler }
];
