#Requires -Version 5.1
<#
.SYNOPSIS
Prepares the pinned InetC plugin and minimum Microsoft runtime requirement.
.DESCRIPTION
No Microsoft software is downloaded or bundled. The minimum runtime is pinned
and checked against MSVC on Windows. -MinimumVersion may raise, never lower, it.
#>
[CmdletBinding()]
param(
    [version]$MinimumVersion,
    [string]$OutputDirectory
)

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'
if (-not $PSBoundParameters.ContainsKey('OutputDirectory')) {
    $OutputDirectory = Join-Path $PSScriptRoot '../src-tauri/windows-resources'
}
# Current stable Microsoft x64 runtime; update deliberately, not during builds.
$pinnedMinimum = [version]'14.51.36247.0'
if (-not $PSBoundParameters.ContainsKey('MinimumVersion')) { $MinimumVersion = $pinnedMinimum }
if ($null -eq $MinimumVersion -or $MinimumVersion -lt $pinnedMinimum) {
    throw "MinimumVersion cannot be lower than the pinned runtime $pinnedMinimum."
}

if ($env:TAURI_ENV_ARCH -and $env:TAURI_ENV_ARCH -notin @('x86_64', 'x64')) {
    throw "The Windows runtime prerequisite supports x64 only, not TAURI_ENV_ARCH=$env:TAURI_ENV_ARCH"
}
foreach ($variable in @('CARGO_BUILD_TARGET', 'DF_BUILD_TARGET_TRIPLE')) {
    $target = [Environment]::GetEnvironmentVariable($variable)
    if ($target -and $target -ne 'x86_64-pc-windows-msvc') {
        throw "The Windows runtime prerequisite requires x86_64-pc-windows-msvc, not ${variable}=$target"
    }
}

if ($MinimumVersion -and ($MinimumVersion.Major -ne 14 -or $MinimumVersion.Revision -lt 0)) {
    throw 'MinimumVersion must be a four-part VC14 version.'
}
if ([Environment]::OSVersion.Platform -eq [PlatformID]::Win32NT) {
    # MSVC's newer headers can require a newer runtime even when DLL names match.
    $vswhere = Join-Path ${env:ProgramFiles(x86)} 'Microsoft Visual Studio/Installer/vswhere.exe'
    if (-not (Test-Path -LiteralPath $vswhere -PathType Leaf)) {
        throw 'vswhere.exe is missing; install the Visual Studio C++ x64 build tools.'
    }
    $runtimes = @(& $vswhere -latest -products '*' -requires Microsoft.VisualStudio.Component.VC.Tools.x86.x64 -find 'VC\Redist\MSVC\*\x64\Microsoft.VC*.CRT\msvcp140.dll')
    if ($LASTEXITCODE -ne 0 -or $runtimes.Count -eq 0) {
        throw 'Could not locate an x64 redistributable in the selected Visual Studio installation.'
    }
    # Side-by-side toolsets can supply several CRTs. Select the newest numeric
    # file version without launching vcvars through a second command shell.
    $requiredVersion = $runtimes | ForEach-Object {
        $info = (Get-Item -LiteralPath $_).VersionInfo
        $candidate = [version]('{0}.{1}.{2}.{3}' -f $info.FileMajorPart, $info.FileMinorPart, $info.FileBuildPart, $info.FilePrivatePart)
        if ($candidate.Major -ne 14) { throw "Unrecognized MSVC runtime version $candidate at $_" }
        $candidate
    } | Sort-Object -Descending | Select-Object -First 1
    if ($MinimumVersion -and $MinimumVersion -lt $requiredVersion) {
        throw "MinimumVersion cannot be older than the selected MSVC runtime $requiredVersion."
    }
}
if (-not $MinimumVersion -or $MinimumVersion.Major -ne 14 -or
    $MinimumVersion.Minor -gt 65535 -or $MinimumVersion.Build -gt 65535 -or $MinimumVersion.Revision -gt 65535) {
    throw 'A valid four-part VC14 minimum runtime version is required.'
}
$version = $MinimumVersion
$nsisConstants = [ordered]@{
    DF_VC_VERSION = $version.ToString()
    DF_VC_MAJOR = $version.Major
    DF_VC_MINOR = $version.Minor
    DF_VC_BUILD = $version.Build
    DF_VC_REVISION = $version.Revision
}
$nsis = @('; Generated by scripts/prepare-windows-runtime.ps1; do not edit.')
foreach ($entry in $nsisConstants.GetEnumerator()) {
    # Numeric file-version components are safe in NSIS preprocessor definitions.
    $nsis += '!define {0} "{1}"' -f $entry.Key, $entry.Value
}
$wix = @(
    '<?xml version="1.0" encoding="utf-8"?>',
    '<Include xmlns="http://schemas.microsoft.com/wix/2006/wi">',
    ('  <?define DF_VC_VERSION="{0}" ?>' -f $version),
    '</Include>'
)
$OutputDirectory = [System.IO.Path]::GetFullPath($OutputDirectory)
[void](New-Item -ItemType Directory -Path $OutputDirectory -Force)
$encoding = [System.Text.UTF8Encoding]::new($false)

$pluginPin = Get-Content -LiteralPath (Join-Path $PSScriptRoot 'windows-runtime-download-plugin.json') -Raw | ConvertFrom-Json
# Normalize checkout line endings to reproduce the exact tagged upstream notice.
$license = [System.IO.File]::ReadAllText((Join-Path $PSScriptRoot 'inetc-license.txt')).Replace("`r`n", "`n")
$sha256 = [System.Security.Cryptography.SHA256]::Create()
try {
    $licenseHash = [BitConverter]::ToString($sha256.ComputeHash($encoding.GetBytes($license))).Replace('-', '')
} finally {
    $sha256.Dispose()
}
if ($licenseHash -ne $pluginPin.licenseSha256) { throw 'The InetC license notice differs from the pinned upstream notice.' }
$pluginDirectory = Join-Path $OutputDirectory 'nsis-plugins'
$pluginPath = Join-Path $pluginDirectory 'x86-unicode/INetC.dll'
$pluginValid = (Test-Path -LiteralPath $pluginPath -PathType Leaf) -and
    ((Get-FileHash -LiteralPath $pluginPath -Algorithm SHA256).Hash -eq $pluginPin.pluginSha256)
if (-not $pluginValid) {
    $work = Join-Path ([System.IO.Path]::GetTempPath()) ('dragonfruit-inetc-' + [guid]::NewGuid().ToString('N'))
    [void](New-Item -ItemType Directory -Path $work)
    try {
        [Net.ServicePointManager]::SecurityProtocol = [Net.ServicePointManager]::SecurityProtocol -bor [Net.SecurityProtocolType]::Tls12
        $archivePath = Join-Path $work 'InetC.zip'
        Invoke-WebRequest -UseBasicParsing -Uri $pluginPin.url -OutFile $archivePath
        if ((Get-FileHash -LiteralPath $archivePath -Algorithm SHA256).Hash -ne $pluginPin.sha256) {
            throw 'The downloaded InetC archive does not match its pinned SHA-256.'
        }
        Add-Type -AssemblyName System.IO.Compression.FileSystem
        $archive = [System.IO.Compression.ZipFile]::OpenRead($archivePath)
        $candidatePath = Join-Path $work 'INetC.dll'
        try {
            $entry = $archive.GetEntry('x86-unicode/INetC.dll')
            if ($null -eq $entry) { throw 'The pinned InetC archive has no x86-Unicode plugin.' }
            [System.IO.Compression.ZipFileExtensions]::ExtractToFile($entry, $candidatePath)
        } finally {
            $archive.Dispose()
        }
        if ((Get-FileHash -LiteralPath $candidatePath -Algorithm SHA256).Hash -ne $pluginPin.pluginSha256) {
            throw 'The extracted InetC plugin does not match its pinned SHA-256.'
        }
        [void](New-Item -ItemType Directory -Path (Split-Path -Parent $pluginPath) -Force)
        Copy-Item -LiteralPath $candidatePath -Destination $pluginPath -Force
    } finally {
        Remove-Item -LiteralPath $work -Recurse -Force
    }
}
# WiX in the pinned Tauri bundler keeps the source basename for mapped resources.
[System.IO.File]::WriteAllText((Join-Path $pluginDirectory 'InetC.txt'), $license, $encoding)
Write-Host "Prepared checksum-pinned InetC $($pluginPin.version) HTTPS plugin and license notice."

[System.IO.File]::WriteAllText((Join-Path $OutputDirectory 'runtime-version.nsh'), (($nsis -join "`n") + "`n"), $encoding)
[System.IO.File]::WriteAllText((Join-Path $OutputDirectory 'runtime-version.wxi'), (($wix -join "`n") + "`n"), $encoding)
Write-Host "Generated x64 runtime prerequisite metadata for $version in $OutputDirectory (no Microsoft payload downloaded)."
$version.ToString()
