// AUTO-GENERATED FILE. DO NOT EDIT.
// Generated by scripts/generate-plugin-registry.mjs

use super::{PluginNetworkResponse, register_plugin};

#[path = "../../plugins/athena/rust/plugin.rs"]
pub mod athena_plugin;

#[path = "../../plugins/athena/rust/network.rs"]
pub mod athena_network;

#[allow(dead_code)]
pub const GENERATED_BUILTIN_PLUGIN_IDS: &[&str] = &["athena"];
pub const GENERATED_COMPLEX_PLUGIN_ALLOWLIST_SHA256: &str = "ce36f29e59f3e7776bd0e87b363c61874a07b74da1eeee186a213e07906acd8b";

pub fn register_generated_plugins() -> Result<(), String> {
    register_plugin(athena_plugin::get_plugin_registration())?;
    Ok(())
}

pub async fn dispatch_generated_network_request(
    plugin_id: &str,
    request_json: String,
) -> Result<Option<PluginNetworkResponse>, String> {
    match plugin_id {
        "athena" => {
            let response = athena_network::dispatch_plugin_network_request(request_json).await?;
            Ok(Some(PluginNetworkResponse {
                status: response.status,
                body: response.body,
            }))
        }
        _ => Ok(None),
    }
}
