// AUTO-GENERATED FILE. DO NOT EDIT.
// Generated by scripts/generate-plugin-registry.mjs

use super::{PluginNetworkResponse, register_plugin};

#[path = "../../plugins/athena/rust/plugin.rs"]
pub mod athena_plugin;

#[path = "../../plugins/athena/rust/network.rs"]
pub mod athena_network;
#[path = "../../plugins/sdcp-v3/rust/plugin.rs"]
pub mod sdcp_v3_plugin;

#[path = "../../plugins/sdcp-v3/rust/network.rs"]
pub mod sdcp_v3_network;

#[allow(dead_code)]
pub const GENERATED_BUILTIN_PLUGIN_IDS: &[&str] = &["athena", "sdcp-v3"];
pub const GENERATED_COMPLEX_PLUGIN_ALLOWLIST_SHA256: &str = "35e5acebbafdb1d054e3b59789b9e7690b22893e8c7f911dc1710efb776c1dee";

pub fn register_generated_plugins() -> Result<(), String> {
    register_plugin(athena_plugin::get_plugin_registration())?;
    register_plugin(sdcp_v3_plugin::get_plugin_registration())?;
    Ok(())
}

pub async fn dispatch_generated_network_request(
    plugin_id: &str,
    request_json: String,
) -> Result<Option<PluginNetworkResponse>, String> {
    match plugin_id {
        "athena" => {
            let response = athena_network::dispatch_plugin_network_request(request_json).await?;
            Ok(Some(PluginNetworkResponse {
                status: response.status,
                body: response.body,
            }))
        },
        "sdcp-v3" => {
            let response = sdcp_v3_network::dispatch_plugin_network_request(request_json).await?;
            Ok(Some(PluginNetworkResponse {
                status: response.status,
                body: response.body,
            }))
        }
        _ => Ok(None),
    }
}
